version: '3'

services:
   dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nik
      MYSQL_PASSWORD: nik
      MYSQL_DATABASE: mydb
   wordpressos:
     image: wordpress:5.1.1-php7.3-apache
     restart: always
     depends_on: 
       - dbos
     ports:
       - 1234:80
     environment:
       WORDPRESS_DB_HOST: dbos
       WORDPRESS_DB_USER: nik
       WORDPRESS_DB_PASSWORD: nik
       WORDPRESS_DB_NAME: mydb
     volumes:
        - wp_storage:/var/www/html
volumes:
   wp_storage:
   mysql_storage:

